### ISSUE TITLE
State of the blog content?

### ISSUE THREAD

**Issue by jt14den** [UCLA-DataSquad/ucla-datasquad.github.io#23]
@emilygong-zhuying, I hope you are well. I wanted to see if all the work was checked into this repo? The converting of recent article to markdown and changes to make this site have a blog. I'm going to work on implementing this, but don't want to lose any work.

**Comment by emilygong-zhuying** [comment]
Hi Tim! Thanks - hope you're doing well too! I didn't end up implementing anything concrete yet, so feel free to do anything you want to the repo. Thanks!
